version: '3'

services:

    db:
      build: .docker/postgres
      container_name: bd-nest
      restart: always
      tty: true
      ports:
        - '5432:5432'
      volumes:
        - .docker/dbdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=api-nest

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin_nest
      tty: true
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - '8000:80'
      depends_on:
        - db